---
  # Arquivo para Instalação do MariaDb e Configurações

  - name: Instalando MariaDB
    yum: name={{ item }} state=installed
    with_items:
      - mariadb-server
      - mariadb
      - python
      - MySQL-python
      - libselinux-python
      - libsemanage-python

  - name: start mariadb
    service: name=mariadb state=started enabled=yes

  - name: Criando Usuário de Banco de Dados
    mysql_user: name=aplicacao password=12345 host='%' priv=*.*:ALL,GRANT state=present

  - name: Copiando arquivo de Banco de dados
    template: src=table.sql dest=/root/

  - name: Executar Script de Banco
    mysql_db: state=import name=all target=/root/table.sql
